<?php
$ru_air = array (
                    'Абха' => 'AHB',
                    'Аддис-Абеба' => 'ADD',
                    'Александрия' => 'HBE',
                    'Алматы' => 'ALA',
                    'Амман' => 'AMM',
                    'Ан-Наджаф' => 'NJF',
                    'Асмэра' => 'ASM',
                    'Астана' => 'TSE',
                    'Ахваз' => 'AWZ',
                    'Ахмадабад' => 'AMD',
                    'Ашхабад' => 'ASB',
                    'Багдад' => 'BGW',
                    'Баку' => 'GYD',
                    'Басра' => 'BSR',
                    'Бахрейн' => 'BAH',
                    'Бейрут' => 'BEY',
                    'Белград' => 'BEG',
                    'Бендер-Аббас' => 'BND',
                    'Бишкек' => 'FRU',
                    'Братислава' => 'BTS',
                    'Бужумбура ' => 'BJM',
                    'Бухарест' => 'OTP',
                    'Вена' => 'XWC',
                    'Гассим' => 'ELQ',
                    'Гоа' => 'GOI',
                    'Дакка' => 'DAC',
                    'Даммам' => 'DMM',
                    'Дар-эс-Салам' => 'DAR',
                    'Дели' => 'DEL',
                    'Джибути' => 'JIB',
                    'Джидда' => 'JED',
                    'Джизан' => 'GIZ',
                    'Джуба' => 'JUB',
                    'Доха' => 'DOH',
                    'Дубай' => 'DXB',
                    'Дубай' => 'DWC',
                    'Душанбе' => 'DYU',
                    'Екатеринбург' => 'SVX',
                    'Ереван' => 'EVN',
                    'Загреб' => 'ZAG',
                    'Занзибар' => 'ZNZ',
                    'Исфахан' => 'IFN',
                    'Кабул' => 'KBL',
                    'Казань' => 'KZN',
                    'Карачи' => 'KHI',
                    'Катманду' => 'KTM',
                    'Кветта' => 'UET',
                    'Кигали' => 'KGL',
                    'Киев' => 'IEV',
                    'Коломбо' => 'CMB',
                    'Коччи' => 'COK',
                    'Краснодар' => 'KRR',
                    'Кувейт' => 'KWI',
                    'Лакхнау' => 'LKO',
                    'Лар' => 'LRR',
                    'Любляна' => 'LJU',
                    'Мале' => 'MLE',
                    'Маскат' => 'MCT',
                    'Маттала' => 'HRI',
                    'Медина' => 'MED',
                    'Мешхед' => 'MHD',
                    'МинеральныеВоды' => 'MRV',
                    'Москва' => 'VKO',
                    'Мултан' => 'MUX',
                    'Мумбаи' => 'BOM',
                    'НижнийНовгород' => 'GOJ',
                    'Одесса' => 'ODS',
                    'Порт-Судан' => 'PZU',
                    'Прага' => 'PRG',
                    'Ростов-на-Дону' => 'ROV',
                    'Салала' => 'SLL',
                    'Самара' => 'KUF',
                    'Сараево' => 'SJJ',
                    'Сиялкот' => 'SKT',
                    'Скопье' => 'SKP',
                    'София' => 'SOF',
                    'Стамбул' => 'SAW',
                    'Табук' => 'TUU',
                    'Таиф' => 'TIF',
                    'Тбилиси' => 'TBS',
                    'Тебриз' => 'TBZ',
                    'Тегеран' => 'IKA',
                    'Тируванантапурам' => 'TRV',
                    'Уфа' => 'UFA',
                    'Фейсалабад' => 'LYP',
                    'Хайдарабад' => 'HYD',
                    'Хаиль' => 'HAS',
                    'Хамадан' => 'HDM',
                    'Харгейса' => 'HGA',
                    'Хартум' => 'KRT',
                    'Ченнаи' => 'MAA',
                    'Читтагонг' => 'CGP',
                    'Шираз' => 'SYZ',
                    'Шымкент' => 'CIT',
                    'Эль-Джауф' => 'AJF',
                    'Эль-Хуфуф' => 'HOF',
                    'Энтеббе' => 'EBB',
                    'Эрбиль' => 'EBL',
                    'Эр-Рияд' => 'RUH',
                    'Янбу' => 'YNB'
    );

$airports = array(
					'ADA' => 'Adana',
					'GZP' => 'Alanya - Gazipasa',
					'ALA' => 'Almaty',
					'MZH' => 'Amasya-Merzifon',
					'AMS' => 'Amsterdam',
					'ESB' => 'Ankara',
					'AYT' => 'Antalya',
					'ATH' => 'Athens',
					'BGW' => 'Baghdad',
					'BAH' => 'Bahrain',
					'EDO' => 'Balikesir-Edremit',
					'BCN' => 'Barcelona',
					'BSL' => 'Basel - Mulhouse',
					'BAL' => 'Batman',
					'BEY' => 'Beirut',
					'BEG' => 'Belgrade',
					'SXF' => 'Berlin-Schonefeld',
					'FRU' => 'Bishkek',
					'BJV' => 'Bodrum',
					'BLQ' => 'Bologna',
					'CRL' => 'Brussels-Charleroi',
					'OTP' => 'Bucharest-Otopeni',
					'BUD' => 'Budapest',
					'CGN' => 'Cologne',
					'CPH' => 'Copenhagen',
					'DLM' => 'Dalaman',
					'DEL' => 'Delhi',
					'DNZ' => 'Denizli',
					'DIY' => 'Diyarbakir',
					'DOH' => 'Doha',
					'DXB' => 'Dubai',
					'DUS' => 'Dusseldorf',
					'EZS' => 'Elazig',
					'EBL' => 'Erbil',
					'ERC' => 'Erzincan',
					'ERZ' => 'Erzurum',
					'FRA' => 'Frankfurt - Main',
					'GZT' => 'Gaziantep',
					'GVA' => 'Geneva',
					'HAM' => 'Hamburg',
					'HAJ' => 'Hannover',
					'HTY' => 'Hatay',
					'HRG' => 'Hurghada',
					'IST_SAW' => 'Istanbul All',
					'IST' => 'Istanbul-Ataturk',
					'SAW' => 'Istanbul-S.Gokcen',
					'ADB' => 'Izmir',
					'KCM' => 'Kahramanmaras',
					'KSY' => 'Kars',
					'KFS' => 'Kastamonu',
					'ASR' => 'Kayseri',
					'HRK' => 'Kharkiv',
					'KYA' => 'Konya',
					'KRR' => 'Krasnodar',
					'KUT' => 'Kutaisi',
					'KWI' => 'Kuwait',
					'ECN' => 'Lefkosa - N. Cyprus',
					'LEJ' => 'Leipzig',
					'STN_LHR_LGW' => 'London All',
					'LGW' => 'London-Gatwick',
					'STN' => 'London-Stansted',
					'LWO' => 'Lviv',
					'LYS_EBU' => 'Lyon All',
					'EBU' => 'Lyon-Saint Etienne',
					'LYS' => 'Lyon-Saint Exupery',
					'MAD' => 'Madrid - Barajas',
					'MCX' => 'Makhachkala',
					'MLX' => 'Malatya',
					'MQM' => 'Mardin',
					'MRS' => 'Marseille',
					'BGY_MXP' => 'Milan All',
					'BGY' => 'Milan-Bergamo',
					'MXP' => 'Milan-Malpensa',
					'MRV' => 'Mineralnye Vody',
					'DME' => 'Moscow - Domodedovo',
					'MUC' => 'Munich',
					'FMO' => 'Munster',
					'MSR' => 'Mus',
					'NAV' => 'Nevsehir',
					'NCE' => 'Nice',
					'OVB' => 'Novosibirsk',
					'NUE' => 'Nuremberg',
					'OGU' => 'Ordu-Giresun',
					'OSS' => 'Osh',
					'OSL' => 'Oslo',
					'VDA' => 'Ovda',
					'ORY' => 'Paris-Orly(Sud)',
					'PRG' => 'Prague',
					'PRN' => 'Pristina',
					'FCO' => 'Rome-Fiumicino',
					'SZF' => 'Samsun',
					'GNY' => 'Sanliurfa',
					'SJJ' => 'Sarajevo',
					'SSH' => 'Sharm el-Sheikh',
					'VAS' => 'Sivas',
					'SKP' => 'Skopje',
					'ARN' => 'Stockholm - Arlanda',
					'STR' => 'Stuttgart',
					'TBS' => 'Tbilisi',
					'IKA' => 'Tehran - IKA',
					'TLV' => 'Tel Aviv - Ben Gurion',
					'TIA' => 'Tirana',
					'TZX' => 'Trabzon',
					'URC' => 'Urumqi',
					'VAN' => 'Van',
					'VIE' => 'Vienna',
					'SVX' => 'YEKATERINBURG',
					'OZH' => 'Zaporizhia',
					'ZRH' => 'Zurich'
				);

function post_content ($url,$postdata) {
	
$uagent = "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.80 Safari/537.36";

$ch = curl_init( $url );
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
curl_setopt($ch, CURLOPT_HEADER, false);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, 1);
curl_setopt($ch, CURLOPT_ENCODING, "gzip, deflate");
curl_setopt($ch, CURLOPT_USERAGENT, $uagent);
curl_setopt($ch, CURLOPT_TIMEOUT, 120);
curl_setopt($ch, CURLOPT_FAILONERROR, 1);
curl_setopt($ch, CURLOPT_AUTOREFERER, 1);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $postdata);

$content = curl_exec( $ch );
$content = str_get_html($content);

return $content;
} 				
?>